### ISSUE TITLE
`-u` REJECTED for current HGVS version

### ISSUE THREAD

**Issue by liserjrqlxue** [ltnetcase/BedAnno#13]
in https://varnomen.hgvs.org/recommendations/open-issues/
format like `c.-237-u29A>G` is rejected
![image](https://user-images.githubusercontent.com/5977521/108931407-8f7b9880-7682-11eb-943a-109bc699e878.png)

I simply change `$cDot` for my own use. But I think you can go further If you will.
![image](https://user-images.githubusercontent.com/5977521/108931295-5fcc9080-7682-11eb-94d2-489e34f6480d.png)

`+d` is similar case. Since no example case to test in hand and less to occur, I have not modify it yet.

**Comment by ltnetcase** [comment]
I have suggest HGVS to reconsider this point, and gives the reason why it is better to use '-u' style, but no reply.
here is the [link](https://www.facebook.com/permalink.php?story_fbid=3000181773354293&id=608154499223711)

**Comment by ltnetcase** [comment]
I add standard_cHGVS for the required HGVS format for this case from release [1.2.3](https://github.com/ltnetcase/BedAnno/releases/tag/1.2.3).
Is it ok?
