### ISSUE TITLE
codon different for mitochondrion

### ISSUE THREAD

**Issue by liserjrqlxue** [ltnetcase/BedAnno#14]
![3781e068630cca4bfabb1333c8d73ba](https://user-images.githubusercontent.com/5977521/109592412-32805680-7b4a-11eb-89f6-467aca243b4e.png)

**Comment by ltnetcase** [comment]
收到，线粒体的我回头抽空系统弄一下。

**Comment by ltnetcase** [comment]
我看了一下，这个原来就已经是通过 translate 方法中对 mito 的转录本翻译的时候，进行了兼容了。不过不是标准的转录本的名字，编码蛋白的基因的转录本进行了 ”NM_MT-" 前缀标记的。如果没有使用对应的转录本命名，会无法生效。这个是原先数据库配置上需要匹配的地方。
代码在 https://github.com/ltnetcase/BedAnno/blob/0b8e5f9b1f0bc3d7c687244865d4f54fc8c17c3e/lib/BedAnno.pm#L4199
补丁代码 https://github.com/ltnetcase/BedAnno/blob/0b8e5f9b1f0bc3d7c687244865d4f54fc8c17c3e/lib/BedAnno.pm#L5574
