### ISSUE TITLE
writing makefile error

### ISSUE THREAD

**Issue by annabi1993** [ltnetcase/BedAnno#9]
I run command `perl Makefile.PL`,there is a warning like this:
`Warning: prerequisite Tabix v0.2.5 not found.
Generating a Unix-style Makefile
Writing Makefile for BedAnno
Writing MYMETA.yml and MYMETA.json`
then I run `make`,the result like this:
`Manifying 1 pod document`
next I run `make test`,there is an error:
`Skip blib/lib/BedAnno.pm (unchanged)
PERL_DL_NONLAZY=1 "/datapool/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/BedAnno.t .. Can't locate Test/Most.pm in @INC (you may need to install the Test::Most module) (@INC contains: /datapool/home/bimiaomiao/tool/BedAnno-master/blib/lib /datapool/home/bimiaomiao/tool/BedAnno-master/blib/arch /datapool/soft/install/lib/perl5/site_perl/5.24.1/x86_64-linux /datapool/soft/install/lib/perl5/site_perl/5.24.1 /datapool/soft/install/lib/perl5/5.24.1/x86_64-linux /datapool/soft/install/lib/perl5/5.24.1 .) at t/BedAnno.t line 29.
BEGIN failed--compilation aborted at t/BedAnno.t line 29.
t/BedAnno.t .. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
Test Summary Report
t/BedAnno.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  1 wallclock secs ( 0.04 usr +  0.03 sys =  0.07 CPU)
Result: FAIL
Failed 1/1 test programs. 0/0 subtests failed.
make: *** [test_dynamic] Error 2`

**Comment by ltnetcase** [comment]
The tabix perl-mod used by this module is outdated, which will need much database updating work, that I have no time to fix.  
Test::Most is just for testing usage, you'd install it yourself using CPAN.
Long time no updating, I'll try fixing the problem later.

**Comment by ltnetcase** [comment]
Though Tabix currently bundled with htslib, you can still find the old version of tabix perl mod [here](https://github.com/samtools/tabix/tree/master/perl)
